# Generated by Django 4.2.2 on 2023-08-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprojectrequestmodel',
            old_name='special_instructions',
            new_name='additional_details',
        ),
        migrations.RenameField(
            model_name='historicalprojectrequestmodel',
            old_name='estimated_start_date',
            new_name='expected_start_date',
        ),
        migrations.RenameField(
            model_name='projectrequestmodel',
            old_name='special_instructions',
            new_name='additional_details',
        ),
        migrations.RenameField(
            model_name='projectrequestmodel',
            old_name='estimated_start_date',
            new_name='expected_start_date',
        ),
        migrations.RemoveField(
            model_name='historicalprojectrequestmodel',
            name='estimated_end_date',
        ),
        migrations.RemoveField(
            model_name='projectrequestmodel',
            name='estimated_end_date',
        ),
        migrations.AddField(
            model_name='historicalprojectrequestmodel',
            name='estimated_project_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrequestmodel',
            name='estimated_project_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresourceaccountmodel',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('INP', 'In process'), ('REJ', 'Rejected'), ('ONB', 'On boarded'), ('CSL', 'Client Shortlisted'), ('ENG', 'Engaged')], default='NEW', max_length=8),
        ),
        migrations.AlterField(
            model_name='resourceaccountmodel',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('INP', 'In process'), ('REJ', 'Rejected'), ('ONB', 'On boarded'), ('CSL', 'Client Shortlisted'), ('ENG', 'Engaged')], default='NEW', max_length=8),
        ),
    ]
